ProtocolConfiguration:
  Magic: 5195086
  MaxTraceableBlocks: 2102400
  SecondsPerBlock: 15
  MemPoolSize: 50000
  StandbyCommittee:
  - 03b209fd4f53a7170ea4444e0cb0a6bb6a53c2bd016926989cf85f9b0fba17a70c
  - 02df48f60e8f3e01c48ff40b9b7f1310d7a8b2a193188befe1c2e3df740e895093
  - 03b8d9d5771d8f513aa0869b9cc8d50986403b78c6da36890638c3d46a5adce04a
  - 02ca0e27697b9c248f6f16e085fd0061e26f44da85b58ee835c110caa5ec3ba554
  - 024c7b7fb6c310fccf1ba33b082519d82964ea93868d676662d4a59ad548df0e7d
  - 02aaec38470f6aad0042c6e877cfd8087d2676b0f516fddd362801b9bd3936399e
  - 02486fd15702c4490a26703112a5cc1d0923fd697a33406bd5a1c00e0013b09a70
  ValidatorsCount: 7
  SeedList:
  - seed1.neo.org:10333
  - seed2.neo.org:10333
  - seed3.neo.org:10333
  - seed4.neo.org:10333
  - seed5.neo.org:10333
  VerifyBlocks: true
  VerifyTransactions: false

ApplicationConfiguration:
  # LogPath could be set up in case you need stdout logs to some proper file.
  # LogPath: "./log/neogo.log"
  DBConfiguration:
    Type: "leveldb" #other options: 'inmemory','redis','boltdb', 'badgerdb'.
    # DB type options. Uncomment those you need in case you want to switch DB type.
    LevelDBOptions:
      DataDirectoryPath: "./chains/mainnet"
  #    RedisDBOptions:
  #      Addr: "localhost:6379"
  #      Password: ""
  #      DB: 0
  #    BoltDBOptions:
  #      FilePath: "./chains/mainnet.bolt"
  #    BadgerDBOptions:
  #      BadgerDir: "./chains/mainnet.badger"
  #  Uncomment in order to set up custom address for node.
  #  Address: 127.0.0.1
  NodePort: 10333
  Relay: true
  DialTimeout: 3
  ProtoTickInterval: 2
  PingInterval: 30
  PingTimeout: 90
  MaxPeers: 100
  AttemptConnPeers: 20
  MinPeers: 5
  RPC:
    Enabled: true
    MaxGasInvoke: 15
    EnableCORSWorkaround: false
    Port: 10332
    TLSConfig:
      Enabled: false
      Port: 10331
      CertFile: serv.crt
      KeyFile: serv.key
  Prometheus:
    Enabled: true
    Port: 2112
  Pprof:
    Enabled: false
    Port: 2113
