ProtocolConfiguration:
  Magic: 56753
  MaxTraceableBlocks: 200000
  SecondsPerBlock: 1
  MemPoolSize: 50000
  StandbyCommittee:
    - 02b3622bf4017bdfe317c58aed5f4c753f206b7db896046fa7d774bbc4bf7f8dc2
  ValidatorsCount: 1
  SeedList:
    - 172.200.0.1:20333
  VerifyBlocks: true
  VerifyTransactions: true

ApplicationConfiguration:
  # LogPath could be set up in case you need stdout logs to some proper file.
  # LogPath: "./log/neogo.log"
  DBConfiguration:
    Type: "leveldb" #other options: 'inmemory','redis','boltdb', 'badgerdb'.
    # DB type options. Uncomment those you need in case you want to switch DB type.
    LevelDBOptions:
      DataDirectoryPath: "/chains/single"
  #    RedisDBOptions:
  #      Addr: "localhost:6379"
  #      Password: ""
  #      DB: 0
  #    BoltDBOptions:
  #      FilePath: "./chains/privnet.bolt"
  #    BadgerDBOptions:
  #      BadgerDir: "./chains/single.badger"
  #  Uncomment in order to set up custom address for node.
  #  Address: 127.0.0.1
  NodePort: 20333
  Relay: true
  DialTimeout: 3
  ProtoTickInterval: 2
  PingInterval: 30
  PingTimeout: 90
  MaxPeers: 10
  AttemptConnPeers: 5
  MinPeers: 0
  RPC:
    Enabled: true
    EnableCORSWorkaround: false
    MaxGasInvoke: 15
    Port: 30333
  Prometheus:
    Enabled: true
    Port: 20001
  Pprof:
    Enabled: false
    Port: 20011
  UnlockWallet:
    Path: "/wallet1.json"
    Password: "one"
