ProtocolConfiguration:
  Magic: 1951352142
  MaxTraceableBlocks: 2102400
  SecondsPerBlock: 15
  MemPoolSize: 50000
  StandbyCommittee:
  - 023e9b32ea89b94d066e649b124fd50e396ee91369e8e2a6ae1b11c170d022256d
  - 03009b7540e10f2562e5fd8fac9eaec25166a58b26e412348ff5a86927bfac22a2
  - 02ba2c70f5996f357a43198705859fae2cfea13e1172962800772b3d588a9d4abd
  - 03408dcd416396f64783ac587ea1e1593c57d9fea880c8a6a1920e92a259477806
  - 02a7834be9b32e2981d157cb5bbd3acb42cfd11ea5c3b10224d7a44e98c5910f1b
  - 0214baf0ceea3a66f17e7e1e839ea25fd8bed6cd82e6bb6e68250189065f44ff01
  - 030205e9cefaea5a1dfc580af20c8d5aa2468bb0148f1a5e4605fc622c80e604ba
  ValidatorsCount: 7
  SeedList:
  - seed1t.neo.org:20333
  - seed2t.neo.org:20333
  - seed3t.neo.org:20333
  - seed4t.neo.org:20333
  - seed5t.neo.org:20333
  VerifyBlocks: true
  VerifyTransactions: false

ApplicationConfiguration:
  # LogPath could be set up in case you need stdout logs to some proper file.
  # LogPath: "./log/neogo.log"
  DBConfiguration:
    Type: "leveldb" #other options: 'inmemory','redis','boltdb', 'badgerdb'.
    # DB type options. Uncomment those you need in case you want to switch DB type.
    LevelDBOptions:
      DataDirectoryPath: "./chains/testnet"
  #    RedisDBOptions:
  #      Addr: "localhost:6379"
  #      Password: ""
  #      DB: 0
  #    BoltDBOptions:
  #      FilePath: "./chains/testnet.bolt"
  #    BadgerDBOptions:
  #      BadgerDir: "./chains/testnet.badger"
  #  Uncomment in order to set up custom address for node.
  #  Address: 127.0.0.1
  NodePort: 20333
  Relay: true
  DialTimeout: 3
  ProtoTickInterval: 2
  PingInterval: 30
  PingTimeout: 90
  MaxPeers: 100
  AttemptConnPeers: 20
  MinPeers: 5
  RPC:
    Enabled: true
    MaxGasInvoke: 15
    EnableCORSWorkaround: false
    Port: 20332
    TLSConfig:
      Enabled: false
      Port: 20331
      CertFile: serv.crt
      KeyFile: serv.key
  Prometheus:
    Enabled: true
    Port: 2112
  Pprof:
    Enabled: false
    Port: 2113
